server:
  port: 8766

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liuc12580/config-2004.git
          search-paths: /
          username:
          password:
          skip-ssl-validation: true
      label: master
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

